version: '3.3'

services:
  memora-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: memora-backend
    restart: unless-stopped
    env_file: .env
    environment:
      - QDRANT_API_URL=$QDRANT_API_URL
      - DATABASE_URL=$DATABASE_URL
      - STRIPE_KEY=$STRIPE_KEY
      - STRIPE_ENDPOINT_KEY=$STRIPE_ENDPOINT_KEY
      - MIXPANEL_TOKEN=$MIXPANEL_TOKEN
      - CLERK_SECRET_KEY=$CLERK_SECRET_KEY
      - VECTOR_URL=$VECTOR_URL
      - RERANKER_URL=$RERANKER_URL

    ports:
      - "3000:3000"
